version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "lockfile-only"
    allow:
      - dependency-type: "all"
    registries:
      - "maven"
    reviewers:
      - "Steve973"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "widen"
    allow:
      - dependency-type: "all"
    registries:
      - "maven"
    reviewers:
      - "Steve973"
