version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: 
      lockfile-only:
        enabled: true
      widen:
        enabled: true
    allow:
      - dependency-type: "all"
    registries:
      - "maven"
    reviewers:
      - "Steve973"
