[versions]
asyncApi = "1.0.0-RC"
bouncycastleFips = "1.0.2.5"
guava = "33.0.0-jre"
junit = "5.10.2"
lombok = "1.18.30"
spotlessPlugin = "6.25.0"

[libraries]
asyncapi-core = { module = "com.asyncapi:asyncapi-core", version.ref = "asyncApi" }
bouncycastle-provider-fips = { module = "org.bouncycastle:bc-fips", version.ref = "bouncycastleFips" }
google-guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
spotless-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotlessPlugin" }
